@startuml
|Professor|
start

|Sistema|
if (Login efetuado?) then (Sim)
else (Não)
    |Professor|
    :Efetuar login;
endif

|Professor|
:Selecionar turma;
:Selecionar aula;
:Definir presenças;

if (Confirmar ação?) then (Sim)
    |Sistema|
    :Submete a grade de presenças;
else (Não)
    |Sistema|
    :Cancela a operação;
endif


stop
@enduml
