@startuml
|Professor|
start

|Sistema|
if (Login efetuado?) then (Sim)
else (Não)
    |Professor|
    :Efetuar login;
endif

|Professor|
:Selecionar turma;
:Mapa de Frequência;

|Sistema|
:Gera lista de frequência;

stop
@enduml
